# We chose not to make these changes
inherit_from: .rubocop_todo.yml

# It's the lowest supported Ruby version
AllCops:
  TargetRubyVersion: 2.3

# It's a matter of taste
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Layout/AlignHash:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Naming/VariableNumber:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false

# We aren't so brave to tackle all these issues right now
Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ClassLength:
  Enabled: false

# Minor annoying issues
Lint/UselessAssignment:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DateTime:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Security/YAMLLoad:
  Enabled: false

